# ["INFO", "DEBUG"]
LOGGING_LEVEL = "DEBUG"
IGNORE_WARNINGS = false
MAX_TASKS = 5
MAX_TASKS_PER_PROXY = 5

#NFT = ""

# If you use mobile proxy
#DEFAULT_PROXY = ""

# !! Doesn't work
#CHANGE_PROXY_URL = ""

# !! Doesn't work
# ["anti-captcha.com", "azcaptcha.com", "deathbycaptcha.com", "rucaptcha.com", "2captcha.com"]
#CAPTCHA_SERVICE = "anti-captcha.com"
#CAPTCHA_SERVICE_API_KEY = ""
